In [12]:
# Initialize a 10x10 matrix (grid)
board = [
    ["Neutral"] * 10 for _ in range(10)
]


In [13]:
# Place Creationist and Evolutionist pieces (just an example setup)
board[0][0] = "Creationist_Earth"
board[0][1] = "Creationist_Water"
board[0][2] = "Creationist_Fire"
board[0][3] = "Creationist_Air"
board[0][4] = "Creationist_Woman"
board[0][5] = "Creationist_Man"
board[0][6] = "Creationist_Air"
board[0][7] = "Creationist_Fire"
board[0][8] = "Creationist_Water"
board[0][9] = "Creationist_Earth"

# Place elements (Earth, Water, Fire, Air) at different positions

board[9][0] = "Evolutionist_Earth"
board[9][1] = "Evolutionist_Water"
board[9][2] = "Evolutionist_Fire"
board[9][3] = "Evolutionist_Air"
board[9][4] = "Evolutionist_Woman"
board[9][5] = "Evolutionist_Man"
board[9][6] = "Evolutionist_Air"
board[9][7] = "Evolutionist_Fire"
board[9][8] = "Evolutionist_Water"
board[9][9] = "Evolutionist_Earth"


In [14]:
def print_board(board):
    for row in board:
        print(" | ".join([str(cell).ljust(20) for cell in row]))
        print("-" * 100)

print_board(board)


Creationist_Earth    | Creationist_Water    | Creationist_Fire     | Creationist_Air      | Creationist_Woman    | Creationist_Man      | Creationist_Air      | Creationist_Fire     | Creationist_Water    | Creationist_Earth   
----------------------------------------------------------------------------------------------------
Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral             
----------------------------------------------------------------------------------------------------
Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral             
----------------------------------------------------------------------------------------------------
Neutral      

In [15]:
# Example: Water moves from (9, 2) to (8, 2)
board[8][3] = "Evolutionist_Air"  # Set the target square to Water
board[9][3] = "Neutral"  # The source square becomes neutral again
# In order to check make the changes here.

In [16]:
def get_state_vector(board):
    # Define a mapping of board elements to their corresponding values
    cell_mapping = {
        "Neutral": 0,
        "Creationist_Man": 1,
        "Creationist_Woman": 2,
        "Evolutionist_Man": 3,
        "Evolutionist_Woman": 4,
        "Creationist_Earth": 5,
        "Creationist_Water": 6,
        "Creationist_Fire": 7,
        "Creationist_Air": 8,
        "Evolutionist_Earth": 9,
        "Evolutionist_Water": 10,
        "Evolutionist_Fire": 11,
        "Evolutionist_Air": 12
    }

    state_vector = []
    for row in board:
        for cell in row:
            # Use the mapping to append values, default to -1 if not found
            state_vector.append(cell_mapping.get(cell, -1))
    
    return state_vector

# Convert the 10x10 board to a state vector
state_vector = get_state_vector(board)

# Print the resulting state vector
print(state_vector)  # Prints the state vector representing the 10x10 grid


[5, 6, 7, 8, 2, 1, 8, 7, 6, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 9, 10, 11, 0, 4, 3, 12, 11, 10, 9]


In [17]:

print(board)


[['Creationist_Earth', 'Creationist_Water', 'Creationist_Fire', 'Creationist_Air', 'Creationist_Woman', 'Creationist_Man', 'Creationist_Air', 'Creationist_Fire', 'Creationist_Water', 'Creationist_Earth'], ['Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral'], ['Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral'], ['Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral'], ['Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral'], ['Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral'], ['Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral'], ['Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral'], ['Neutral',

In [18]:
matrix_board = [state_vector[i:i + 10] for i in range(0, len(state_vector), 10)]



In [19]:
import numpy as np

matrix_board = np.array(state_vector).reshape(10, 10)


In [20]:
for row in matrix_board:
    print(row)




[5 6 7 8 2 1 8 7 6 5]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[ 0  0  0 12  0  0  0  0  0  0]
[ 9 10 11  0  4  3 12 11 10  9]


In [21]:
print_board(board)

Creationist_Earth    | Creationist_Water    | Creationist_Fire     | Creationist_Air      | Creationist_Woman    | Creationist_Man      | Creationist_Air      | Creationist_Fire     | Creationist_Water    | Creationist_Earth   
----------------------------------------------------------------------------------------------------
Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral             
----------------------------------------------------------------------------------------------------
Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral              | Neutral             
----------------------------------------------------------------------------------------------------
Neutral      

In [22]:
import pygame

# Initialize Pygame
pygame.init()

# Constants
SCREEN_SIZE = 600
GRID_SIZE = 10
CELL_SIZE = SCREEN_SIZE // GRID_SIZE
COLORS = {
    "Neutral": (200, 200, 200),
    "Earth": (34, 139, 34),  # Green
    "Water": (0, 0, 255),    # Blue
    "Fire": (255, 0, 0),     # Red
    "Air": (255, 255, 0),    # Yellow,
    "Creationist_Man": (255, 165, 0),
    "Creationist_Woman": (255, 140, 0),
    "Evolutionist_Man": (128, 0, 128),
    "Evolutionist_Woman": (147, 112, 219),
}

# Power hierarchy (cyclical dominance)
ELEMENT_POWER = {
    "Earth": "Water",
    "Water": "Fire",
    "Fire": "Air",
    "Air": "Earth"
}

# Game Board
board = [["Neutral"] * GRID_SIZE for _ in range(GRID_SIZE)]

# Place Creationist and Evolutionist pieces
board[0][0], board[0][9] = "Earth", "Earth"
board[0][1], board[0][8] = "Water", "Water"
board[0][2], board[0][7] = "Fire", "Fire"
board[0][3], board[0][6] = "Air", "Air"
board[0][4], board[0][5] = "Creationist_Woman", "Creationist_Man"
board[9][0], board[9][9] = "Earth", "Earth"
board[9][1], board[9][8] = "Water", "Water"
board[9][2], board[9][7] = "Fire", "Fire"
board[9][3], board[9][6] = "Air", "Air"
board[9][4], board[9][5] = "Evolutionist_Woman", "Evolutionist_Man"

# Pygame setup
screen = pygame.display.set_mode((SCREEN_SIZE + 100, SCREEN_SIZE))  # Extra space for element representation
pygame.display.set_caption("OrOgins Game")

# Selected piece and valid moves
selected_piece = None
valid_moves = []


def draw_board():
    """Draw the game board and pieces."""
    for row in range(GRID_SIZE):
        for col in range(GRID_SIZE):
            cell_value = board[row][col]
            color = COLORS.get(cell_value, COLORS["Neutral"])
            pygame.draw.rect(screen, color, (col * CELL_SIZE, row * CELL_SIZE, CELL_SIZE, CELL_SIZE))
            pygame.draw.rect(screen, (0, 0, 0), (col * CELL_SIZE, row * CELL_SIZE, CELL_SIZE, CELL_SIZE), 1)

    # Highlight valid moves
    for move in valid_moves:
        pygame.draw.rect(screen, (0, 255, 0), (move[1] * CELL_SIZE, move[0] * CELL_SIZE, CELL_SIZE, CELL_SIZE), 3)

    # Draw element representations on the side
    pygame.draw.rect(screen, COLORS["Earth"], (SCREEN_SIZE + 10, 50, 80, 20))
    pygame.draw.rect(screen, COLORS["Water"], (SCREEN_SIZE + 10, 100, 80, 20))
    pygame.draw.rect(screen, COLORS["Fire"], (SCREEN_SIZE + 10, 150, 80, 20))
    pygame.draw.rect(screen, COLORS["Air"], (SCREEN_SIZE + 10, 200, 80, 20))


def get_valid_moves(row, col):
    """Get valid moves for the selected piece."""
    moves = []
    piece = board[row][col]

    # Determine the element of the piece
    piece_element = None
    for element in ["Earth", "Water", "Fire", "Air"]:
        if element in piece:
            piece_element = element
            break

    if "Man" in piece or "Woman" in piece:
        # Male/Female pieces move diagonally or forward on elemental squares
        directions = [(1, 0), (1, 1), (1, -1)] if "Creationist" in piece else [(-1, 0), (-1, -1), (-1, 1)]
        for dr, dc in directions:
            nr, nc = row + dr, col + dc
            if 0 <= nr < GRID_SIZE and 0 <= nc < GRID_SIZE:
                if board[nr][nc] != "Neutral" and not board[nr][nc].endswith("Man") and not board[nr][nc].endswith("Woman"):
                    moves.append((nr, nc))

    elif piece_element:
        # Elements can move freely over neutral squares or same elements
        directions = [(-1, 0), (1, 0), (0, -1), (0, 1), (-1, -1), (-1, 1), (1, -1), (1, 1)]
        for dr, dc in directions:
            nr, nc = row, col
            while True:
                nr += dr
                nc += dc
                if 0 <= nr < GRID_SIZE and 0 <= nc < GRID_SIZE:
                    target = board[nr][nc]
                    if target == "Neutral" or target == piece:
                        moves.append((nr, nc))
                    else:
                        # Check elemental power hierarchy
                        target_element = None
                        for element in ["Earth", "Water", "Fire", "Air"]:
                            if element in target:
                                target_element = element
                                break
                        if target_element and (ELEMENT_POWER[piece_element] == target_element or target_element == piece_element):
                            moves.append((nr, nc))
                        break  # Stop at the first non-neutral square
                else:
                    break

    return moves


def capture_elements(start, end):
    """Capture weaker elements along the way."""
    sr, sc = start
    er, ec = end
    piece_element = None

    # Get the element of the moving piece (if it's an element piece)
    if "_" in board[sr][sc] and ("Earth" in board[sr][sc] or "Water" in board[sr][sc] or "Fire" in board[sr][sc] or "Air" in board[sr][sc]):
        piece_element = board[sr][sc].split("_")[1]  # Extract 'Earth', 'Water', etc.

    # If the moving piece has no element, skip capture logic
    if not piece_element:
        return

    # Capture logic: Traverse the path from start to end
    dr = 1 if er > sr else -1 if er < sr else 0  # Direction row
    dc = 1 if ec > sc else -1 if ec < sc else 0  # Direction col
    r, c = sr + dr, sc + dc

    while (r, c) != (er, ec):
        # Check the piece on the current square
        if board[r][c] != "Neutral":
            target_piece = board[r][c]
            if "_" in target_piece and ("Earth" in target_piece or "Water" in target_piece or "Fire" in target_piece or "Air" in target_piece):
                target_element = target_piece.split("_")[1]  # Extract 'Earth', 'Water', etc.
                # Check if the moving piece's element is stronger
                if ELEMENT_POWER[piece_element] == target_element:
                    board[r][c] = "Neutral"  # Capture the weaker element
        r += dr
        c += dc



def move_piece(start, end):
    """Move a piece from start to end."""
    global selected_piece, valid_moves
    sr, sc = start
    er, ec = end

    # Capture weaker elements along the way
    capture_elements(start, end)

    # Change neutral squares to match element
    if "Earth" in board[sr][sc] or "Water" in board[sr][sc] or "Fire" in board[sr][sc] or "Air" in board[sr][sc]:
        dr, dc = er - sr, ec - sc
        if abs(dr) + abs(dc) > 1:  # Movement covers multiple squares
            step_r, step_c = dr // abs(dr) if dr != 0 else 0, dc // abs(dc) if dc != 0 else 0
            r, c = sr, sc
            while (r, c) != (er, ec):
                r += step_r
                c += step_c
                if board[r][c] == "Neutral":
                    board[r][c] = board[sr][sc]  # Change to the moving piece's element

    # Move the piece
    board[er][ec] = board[sr][sc]
    board[sr][sc] = "Neutral"  # Set starting position to neutral
    selected_piece = None
    valid_moves = []


# Main game loop
running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        elif event.type == pygame.MOUSEBUTTONDOWN:
            x, y = event.pos
            col, row = x // CELL_SIZE, y // CELL_SIZE  # Convert pixel to grid coordinates

            if selected_piece:
                # If a piece is selected, check if clicked square is a valid move
                if (row, col) in valid_moves:
                    move_piece(selected_piece, (row, col))
                else:
                    # Deselect the piece if clicked elsewhere
                    selected_piece = None
                    valid_moves = []
            else:
                if board[row][col] != "Neutral":
                    selected_piece = (row, col)
                    valid_moves = get_valid_moves(row, col)

    # Redraw the screen
    screen.fill((255, 255, 255))  # Clear screen
    draw_board()
    pygame.display.flip()

pygame.quit()
